FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ml-pipeline/ /app/ml-pipeline/
COPY backend/models/ /app/backend/models/

CMD ["python", "ml-pipeline/training/train.py"]
